### ISSUE TITLE
Game becomes really stuttery when running the auto splitter

### ISSUE THREAD

**Issue by DeaTh-G** [SonicSpeedrunning/LiveSplit.SonicFrontiers#6]
I've been running a category not officially hosted on speedrun.com for a few days now and I wanted to use the splitter made by the community with my own run.

After running a bit with the AutoSplitter my PC also starts dropping the GPU driver for some odd reason and producing the following log in Event Viewer. This persists until a reboot, even after I close LiveSplit for some reason (although while writing this it didn't happen again after closing LiveSplit).
![image](https://user-images.githubusercontent.com/55578911/204289081-13f51cbb-bcea-4757-96be-e30ab8656126.png)

Here's a short video of the stutters presented with LiveSplit and the AutoSplitter running:
https://www.youtube.com/watch?v=QrizCagnWkA

Here's a full run of the category I'm running without any stutters:
https://www.youtube.com/watch?v=9PEyyqskjJI

And important note to add is that I've not yet tried a run without the AutoSplitter and just using LiveSplit as a timer.

Specs:
 - Windows 11 Pro Insider Preview (OS Build 25247.1000)
 - AMD Ryzen 5 2600
 - 16GB DDR4 3000 MHz
 - ZOTAC GAMING GeForce RTX 3080 Trinity OC LHR

**Comment by Jujstme** [comment]
The autosplitter has some (minor, luckily) performance issues due to how it has to look for a specific offset while reading in the game's memory.
As far as I know, anyway, that file is a component of the nvidia driver, and the autosplitter does not use any kernel function outside the ones usually required from memory scanning (OpenProcess, ReadProcessMemory, etc.).

I remember having the gpu driver crash once while playing the game, but that never  happened to me again (though I updated the drivers in the meanwhile).

**Comment by DeaTh-G** [comment]
Just now I got the issue with the AutoSplitter deactivated in LiveSplit and just trying to stick with with manual splitting, but it still caused the stuttering issues and the gpu driver reset. I guess this is an issue with just LiveSplit itself on my system.

Edit: fixed typos.

**Comment by Jujstme** [comment]
Maybe it's an issue with livesplit itself rather than the autosplitter?

**Comment by DeaTh-G** [comment]
It seems to be so.
